shop/detail/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # url(r'^$',views.index,name='index'),
    url(r'^detail/$',views.detail,name='detail'),
]

shop/goodslist/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^list/$', views.list, name='list'),
  
]
 # url(r'^list/$',views.list,name='list'),

shop/index/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$',views.index,name='indexPage'),
    url(r'^aboutus/$',views.aboutus,name='aboutus'),
    url(r'^callus/$',views.callus,name='callus'),
    url(r'^joinus/$',views.joinus,name='joinus'),
    url(r'^loginOut/$',views.loginOut,name='loginOut')
]

shop/registerLogin/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^regcheck/$',views.regcheck,name='regcheck'),
]

shop/shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^',include('index.urls',namespace='index')),
    url(r'^',include('registerLogin.urls',namespace='registerLogin')),
    url(r'^',include('goodslist.urls',namespace='goodslist')),
    url(r'^',include('usercenter.urls',namespace='usercenter')),
    url(r'^',include('detail.urls',namespace='detail')),
]

shop/usercenter/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^user_center_info/$',views.user_center_info,name='user_center_info'),
    url(r'^user_center_order/$',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/$',views.user_center_site,name='user_center_site'),
    url(r'^areal/$',views.areal,name='areal'),
    url(r'^areal([0-9]+)/$',views.areal2,name='areal2'),
]

shop/detail/models.py
# coding=utf-8
from django.db import models
from datetime import datetime
from tinymce.models import HTMLField


# 用户表

class UserInfo(models.Model):
    uName = models.CharField(max_length=30)
    uPassword = models.CharField(max_length=20)
    uEmail = models.CharField(max_length=30)
    uPhoneNumber = models.CharField(max_length=15, null=True)
    uAddr = models.CharField(max_length=50, null=True, blank=True)
    uRegDate = models.DateTimeField()
    isDelete = models.BooleanField(default=False)
    extra = models.CharField(max_length=20,null=True,blank=True) #预留

    class Meta():
        db_table = 'userinfo'

    def __str__(self):
        return self.uName.encode('utf-8')

# 省市区表

class AreaInfo(models.Model):
    aTitle = models.CharField(max_length=20)
    aParent = models.ForeignKey('self', null=True, blank=True)

    class Meta():
        db_table = 'areainfo'

    def __str__(self):
        return self.atitle.encode('utf-8')

# 地址信息表

class AddrInfo(models.Model):
    aName = models.CharField(max_length=30)
    aProvince = models.CharField(max_length=15)
    aCity = models.CharField(max_length=15)
    aDis = models.CharField(max_length=15, null=True, blank=True)
    aAddressee = models.CharField(max_length=20)  # 收信人
    aDetaAddr = models.CharField(max_length=30)
    aPostCode = models.CharField(max_length=10, null=True, blank=True)
    aPhoneNumber = models.CharField(max_length=15)
    isDelete = models.BooleanField(default=False)
    aDefaultAddr = models.BooleanField(default=False)  # 默认地址
    extra = models.CharField(max_length=20,null=True,blank=True) #预留
    aUser = models.ForeignKey('UserInfo')

    class Meta():
        db_table = 'addrinfo'

    def __str__(self):
        return self.aName.encode('utf-8')

# 商品种类表

class GoodSort(models.Model):
    sortName = models.CharField(max_length=10)
    sortPic = models.ImageField(upload_to='uploads/')
    extra = models.CharField(max_length=20,null=True,blank=True) #预留

    class Meta():
        db_table = 'goodsort'

    def __str__(self):
        return self.sortName.encode('utf-8')

# 商品表

class Goods(models.Model):
    goodsName = models.CharField(max_length=30)
    goodsDesc = models.CharField(max_length=80)
    goodsPrice = models.DecimalField(max_digits=7, decimal_places=2)
    goodsDetail = HTMLField()
    imgPath = models.ImageField(upload_to='uploads/')
    saleCount = models.IntegerField(default=0)
    gPubdate=models.DateTimeField()
    extra = models.CharField(max_length=20,null=True,blank=True) #预留
    goodSort = models.ForeignKey('GoodSort')

    class Meta():
        db_table = 'goods'

    def __str__(self):
        return self.goodsName.encode('utf-8')

# 商品评论

class GoodsComment(models.Model):
    userName = models.CharField(max_length=30)
    commentDate = models.DateTimeField()
    comment = HTMLField()
    goods = models.ForeignKey('Goods')
    extra = models.CharField(max_length=20,null=True,blank=True) #预留

    class Meta():
        db_table = 'goodscomment'

    def __str__(self):
        return self.userName.encode('utf-8')

# 购物车表

class Cart(models.Model):
    goodsName = models.CharField(max_length=30)
    buyCount = models.IntegerField(default=1)
    isDelete = models.BooleanField(default=False)
    userCart = models.ForeignKey('UserInfo')
    extra = models.CharField(max_length=20,null=True,blank=True) #预留

    class Meta():
        db_table = 'cart'

    def __str__(self):
        return self.goodsName.encode('utf-8')

# 订单表

class Orders(models.Model):
    goodsName = models.CharField(max_length=30)
    goodsPrice = models.DecimalField(max_digits=7, decimal_places=2)
    buyCount = models.IntegerField()
    isFinish = models.BooleanField(default=False)
    isDelete = models.BooleanField(default=False)
    orderTime = models.DateTimeField()
    extra = models.CharField(max_length=20,null=True,blank=True) #预留
    userOrder = models.ForeignKey('UserInfo')

    class Meta():
        db_table = 'orders'

    def __str__(self):
        return self.goodsName.encode('utf-8')

# 最近浏览
class RecentSee(models.Model):
    goodsName=models.CharField(max_length=30)
    extra = models.CharField(max_length=20,null=True,blank=True) #预留
    user=models.ForeignKey('UserInfo')

    class Meta():
        db_table='recentsee'

    def __str__(self):
        return self.goodsName.encode('utf-8')

shop/detail/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import *
from models import *
from datetime import datetime



def detail(request):
	list1 = Goods.objects.all()[0:1]

	# list1 = goods.goodscomment_set.all()
	# list2 =GoodSort.objects.filter(goodSort_id=1)
	dic ={'list':list1,

		'comment':list1,

	}


	return render(request,'freshFruit/detail.html',dic)




				
			
			

shop/templates/freshFruit/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
		<title>{%block title%}{%endblock%} </title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
		<script type="text/javascript">
			$(function(){
				if ($('.login_info em').html() != ''){
					$('.login_info').show();
					$('.login_btn').hide();
					$('#login_btn_out').show();
				}
				else
				{
					$('.login_info').hide();
					$('.login_btn').show();
					$('#login_btn_out').hide();
				}
			})	
		</script>
</head>
<body>
{%block top%}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{uname}}</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'registerLogin:login' %}">登陆</a>
					<span>|</span>
					<a href="{% url 'registerLogin:register' %}">注册</a>
				</div>
				<div class="login_btn fl" id='login_btn_out'>
					<span>|</span>
					<a href="/loginOut/">退出</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{%endblock%}

{%block menu%}{%endblock%}

{%block content%}{%endblock%}

{%block class%}<div class="footer">{%endblock%}
		<div class="foot_link">
			<a href="{% url 'index:aboutus' %}">关于我们</a>
			<span>|</span>
			<a href="{% url 'index:callus' %}">联系我们</a>
			<span>|</span>
			<a href="{% url 'index:joinus' %}">招聘人才</a>
			<span>|</span>
			<a href="{% url 'index:indexPage' %}">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-6543888    京ICP备654388888号</p>
	</div>
</body>
</html>

shop/templates/freshFruit/base_index.html
{%extends 'freshFruit/base.html'%}
{% load static from staticfiles %}
{%block title%}天天生鲜-用户中心{%endblock%}

{%block menu%}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<div class="search_bar clearfix">
		<a href="{% url 'index:indexPage' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="cart.html" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{%block cartnumber%}0{%endblock%}</div>
		</div>
	</div>
	{%block navlist%}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goodslist:list'%}?order=id&&sort=1&&page={{goodslist.pindex}}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goodslist:list'%}?order=id&&sort=2&&page={{goodslist.pindex}}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goodslist:list'%}?order=id&&sort=3&&page={{goodslist.pindex}}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goodslist:list'%}?order=id&&sort=4&&page={{goodslist.pindex}}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goodslist:list'%}?order=id&&sort=5&&page={{goodslist.pindex}}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goodslist:list'%}?order=id&&sort=6&&page={{goodslist.pindex}}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'index:indexPage' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	{%endblock%}
{%endblock%}

shop/templates/freshFruit/index.html
{%extends 'freshFruit/base_index.html'%}

{% load static from staticfiles %}

{%block title%}天天生鲜首页{%endblock%}

{%block cartnumber%}2{%endblock%}

{%block content%}
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for temp in sorts %}
			<li><a href="#model0{{temp.id}}" class="{{temp.sortClass}}">{{temp.sortName}}</a></li>
			{% endfor temp %}
		</ul>

		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
		{% for s1 in sortMs1 %}
			<h3 class="fl" id="model01">{{s1.sortName}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for ot1 in other1 %}
				<!-- 其他3条商品的名字 -->
					<a href="{% url 'index:callus' %}?sortId={{ot1.id}}">{{ot1.goodsName}}</a>
				{% endfor ot1 %}
			</div>
			<a href="{% url 'goodslist:list'%}?order=id&&sort={{s1.id}}&&page={{goodslist.pindex}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/{{s1.sortPic}}"></div>
		{% endfor s1 %}
			<ul class="goods_list fl">
			{% for goosMs1 in goodsMsg1 %}
				<li>
					<h4><a href="{% url 'index:callus' %}?sortId={{goosMs1.id}}">{{goosMs1.goodsName}}</a></h4>
					<a href="{% url 'index:callus' %}?sortId={{goosMs1.id}}"><img src="/static/{{goosMs1.imgPath}}"></a>
					<div class="prize">¥ {{goosMs1.goodsPrice}}</div>
				</li>
			{% endfor goosMs1 %}
			</ul>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
		{% for s2 in sortMs2 %}
			<h3 class="fl" id="model02">{{s2.sortName}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for ot2 in other2 %}
					<a href="{% url 'index:callus' %}?sortId={{ot2.id}}">{{ot2.goodsName}}</a>
				{% endfor ot2 %}		
			</div>
			<a href="{% url 'goodslist:list'%}?order=id&&sort={{s2.id}}&&page={{goodslist.pindex}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/{{s2.sortPic}}"></div>
		{% endfor s2 %}
			<ul class="goods_list fl">
			{% for goosMs2 in goodsMsg2 %}
				<li>
					<h4><a href="{% url 'index:callus' %}?sortId={{goosMs2.id}}">{{goosMs2.goodsName}}</a></h4>
					<a href="{% url 'index:callus' %}?sortId={{goosMs2.id}}"><img src="/static/{{goosMs2.imgPath}}"></a>
					<div class="prize">¥ {{goosMs2.goodsPrice}}</div>
				</li>
			{% endfor goosMs2 %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
		{% for s3 in sortMs3%}
			<h3 class="fl" id="model03">{{s3.sortName}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for ot3 in other3 %}
					<a href="{% url 'index:callus' %}?sortId={{ot3.id}}">{{ot3.goodsName}}</a>
				{% endfor ot3 %}
			</div>
			<a href="{% url 'goodslist:list'%}?order=id&&sort={{s3.id}}&&page={{goodslist.pindex}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/{{s3.sortPic}}"></div>
		{% endfor s3 %}
			<ul class="goods_list fl">
			{% for goosMs3 in goodsMsg3 %}
				<li>
					<h4><a href="{% url 'index:callus' %}?sortId={{goosMs3.id}}">{{goosMs3.goodsName}}</a></h4>
					<a href="{% url 'index:callus' %}?sortId={{goosMs3.id}}"><img src="/static/{{goosMs3.imgPath}}"></a>
					<div class="prize">¥ {{goosMs3.goodsPrice}}</div>
				</li>
			{% endfor goosMs3 %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
		{% for s4 in sortMs4%}
			<h3 class="fl" id="model04">{{s4.sortName}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for ot4 in other4 %}
					<a href="{% url 'index:callus' %}?sortId={{ot4.id}}">{{ot4.goodsName}}</a>
				{% endfor ot4 %}
			</div>
			<a href="{% url 'goodslist:list'%}?order=id&&sort={{s4.id}}&&page={{goodslist.pindex}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/{{s4.sortPic}}"></div>
		{% endfor s4 %}
			<ul class="goods_list fl">
					{% for goosMs4 in goodsMsg4 %}
						<li>
							<h4><a href="{% url 'index:callus' %}?sortId={{goosMs4.id}}">{{goosMs4.goodsName}}</a></h4>
							<a href="{% url 'index:callus' %}?sortId={{goosMs4.id}}"><img src="/static/{{goosMs4.imgPath}}"></a>
							<div class="prize">¥ {{goosMs4.goodsPrice}}</div>
						</li>
					{% endfor goosMs4 %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
		{% for s5 in sortMs5 %}
			<h3 class="fl" id="model05">{{s5.sortName}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for ot5 in other5 %}
					<a href="{% url 'index:callus' %}?sortId={{ot5.id}}">{{ot5.goodsName}}</a>
				{% endfor ot5 %}
			</div>
			<a href="{% url 'goodslist:list'%}?order=id&&sort={{s5.id}}&&page={{goodslist.pindex}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/{{s5.sortPic}}"></div>
		{% endfor s5 %}
			<ul class="goods_list fl">
					{% for goosMs5 in goodsMsg5 %}
						<li>
							<h4><a href="{% url 'index:callus' %}?sortId={{goosMs5.id}}">{{goosMs5.goodsName}}</a></h4>
							<a href="{% url 'index:callus' %}?sortId={{goosMs5.id}}"><img src="/static/{{goosMs5.imgPath}}"></a>
							<div class="prize">¥ {{goosMs5.goodsPrice}}</div>
						</li>
					{% endfor goosMs5 %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
		{% for s6 in sortMs6%}
			<h3 class="fl" id="model06">{{s6.sortName}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for ot6 in other6 %}
					<a href="{% url 'index:callus' %}?sortId={{ot6.id}}">{{ot6.goodsName}}</a>
				{% endfor ot6 %}
			</div>
			<a href="{% url 'goodslist:list'%}?order=id&&sort={{s6.id}}&&page={{goodslist.pindex}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/{{s6.sortPic}}"></div>
		{% endfor s6 %}
			<ul class="goods_list fl">
					{% for goosMs6 in goodsMsg6 %}
						<li>
							<h4><a href="{% url 'index:callus' %}?sortId={{goosMs6.id}}">{{goosMs6.goodsName}}</a></h4>
							<a href="{% url 'index:callus' %}?sortId={{goosMs6.id}}"><img src="/static/{{goosMs6.imgPath}}"></a>
							<div class="prize">¥ {{goosMs6.goodsPrice}}</div>
						</li>
					{% endfor goosMs6 %}
			</ul>
		</div>
	</div>
{%endblock%}
{% block navlist %}
{% endblock %}

shop/templates/freshFruit/login.html
{%extends 'freshFruit/base.html'%}
{% load static from staticfiles %}

{%block title%}天天生鲜-登录页{%endblock%}
{%block top%}{%endblock%}


{%block content%}
<div class="login_top clearfix">
		<a href="{% url 'index:indexPage'%}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>	
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'registerLogin:register'%}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'registerLogin:login' %}" method="post">
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">{{error.name}}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">{{error.password}}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="check">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		if ($('.user_error').html() != '') {$('.user_error').show()};
		if ($('.pwd_error').html() != ''){$('.pwd_error').show()};
	</script>
{%endblock%}
{%block class%}<div class="footer no-mp">{%endblock%}

shop/templates/freshFruit/register.html
{%extends 'freshFruit/base.html'%}
{% load static from staticfiles %}

{%block title%}天天生鲜-注册界面{%endblock%}
{%block top%}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js'%}"></script>
{%endblock%}


{%block content%}
<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="{% url 'index:indexPage' %}"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">				
				<h1>用户注册</h1>
				<a href="{% url 'registerLogin:login' %}">登录 </a>
			</div>
			<div class="reg_form clearfix" id='reg_form'>
				<form method="post" action="{% url 'registerLogin:register'%}">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock%}